### PR TITLE
Add source code for registry editor and grapher

### PR DESCRIPTION
**Pull request by maffoo**
I've imported the source code for these two programs from the labrad modules svn repo on sourceforge: http://sourceforge.net/p/labradmodules/code/HEAD/tree/Delphi/

The grapher in particular has had some recent changes that I forgot I had already made there, for example 2D plots that use color fill (instead of just dots) and allow zooming and panning.

I've also updated the icons for the registry editor and grapher, as discussed here: https://github.com/martinisgroup/pyle/issues/191

### CODE REVIEW

**Comment by ejeffrey** [comment]
When I try to load the RegistryEditor project I get an "Error Reading Form" dialog that says "Class TLabRADClient not found..."

It stills seems to work and I can build the registry editor, so I don't know what is going on.

**Comment by maffoo** [comment]
Can you try opening up the api components project and 'installing' the components on your machine? I wonder if that will fix things.

**Comment by maffoo** [comment]
@ejeffrey did you get a chance to try the build again? any other comments or should I go ahead and merge?

**Comment by ejeffrey** [comment]
When I open LabRADComponents.dpk and select "install" I get an error:

Field MainForm.LabRADClient does not have a corresponding component.  Remove the declaration? 

Maybe we can go through this together sometime when you are in town?

**Comment by maffoo** [comment]
Be sure to close the registry project before you open the .dpk. If I don't close the registry project first, I can reproduce the error you're seeing, but if I first close the registry project, the .dpk installs successfully, and the registry project subsequently loads in fine.

**Comment by ejeffrey** [comment]
It turns out "install" doesn't trigger "compile" :).  Compile then install
of the API package fixes the problem.  LGTM.

**Comment by maffoo** [comment]
nice catch! thanks for figuring that out.

**Comment by ejeffrey** [comment]
Also, I don't know what explorere.exe does, and I doubt anyone except maybe
matthew, dan, and jim know either.  If we can find the source for it, lets
put it in the labrad-manager-delphi repo and delete the binary from pyle.

Evan

**Comment by maffoo** [comment]
I vote for remove. It's a very clunky interface to do a small portion of what can be done more simply with an interactive python session.

**Comment by DanielSank** [comment]
+1 for remove.

**Comment by maffoo** [comment]
how about ScreenShotViewer and SweepClient while we're at it?

**Comment by DanielSank** [comment]
Haha, the SweepClient! We should send that to the National Museum of American History.

**Comment by maffoo** [comment]
let's move the discussion here: https://github.com/martinisgroup/pyle/issues/235

**Pull request merged**
